### ISSUE TITLE
Gulpfile doesn't refresh the symlink

### ISSUE THREAD

**Issue by anthonyronda** [vttred/ose#12]
The Gulpfile is intended to unlink and relink the working directory whenever you `gulp link` but there's an error in the logic that prevents this from happening

**Comment by engleback** [comment]
Can we separate build and link, and then create one (distribute?) that does both, I never use the link anyway

**Comment by anthonyronda** [comment]
I put this off while I looked at options for replacing gulp, but frankly I think we might be stuck with it for the foreseeable future. 

> Can we separate build and link, and then create one (distribute?) that does both, I never use the link anyway

This is coming

**Comment by anthonyronda** [comment]
@engleback I've now merged your requested change in #71

**Comment by anthonyronda** [comment]
I'm closing this in favor of #106
