### ISSUE TITLE
[Enhancement] A new setting to toggle Ctrl/Cmd+click behavior when rolling attacks

### ISSUE THREAD

**Issue by woodwardj** [vttred/ose#124]
If I need to roll multiple NPC attacks, it is nice to just click x number of attacks instead of clicking the attack and then the pop-up for each attack.   It seems that the default should be no situational modifiers, so that should require the least number of clicks.  DCC has a nice setup where you Ctrl-Click to modify a dice roll, or it just rolls with the default roll settings.

**Comment by woodwardj** [comment]
I just realized that Ctrl-click can be used to quickly roll without the modifier popup dialog.   It would be nice to have the option to invert the behavior but it is completely workable as is.

**Comment by anthonyronda** [comment]
Speaking of Ctrl-click, it appears to be broken for me on Mac 😮. Neither Ctl+click nor Cmd+click do anything

I believe we aren't using the V9 keybind API which would fix that

**Comment by praetor** [comment]
Having a modification dialog option for other non-attack rolls would be nice. For abilities which are clicked to roll, being able to add situational modifiers would be a great enhancement.

**Comment by anthonyronda** [comment]
We've just had a request on the OSE Community Discord for the same feature. 

Changing the issue title to help with discovery

### Current behavior 

When you click on an attack roll, there's a modifier dialog box that asks to input a roll input before rolling. You may skip this by holding ctl/cmd as you click. There is not a setting to invert, showing the prompt only while holding ctl/cmd. There is not a modifier window for every type of item roll.

### Requested behavior

There is a new setting toggle the user can select. It will allow users to make all attack rolls without showing the modifier dialog box.
