### ISSUE TITLE
Stacked items disappearing

### ISSUE THREAD

**Issue by HarringtonE4** [vttred/ose#125]
Issue:
Stacked item counts reset in player inventories.

When an item is given to a player, and then the number of items is changed in the inventory menu (Arrows, Coins, Gems, etc...) that number remains until a new item is given to that player. Once a new item is inserted into the inventory, the stacked items are all reset to 1.

This has been reproducible for me with all modules turned off and only using the base OSE setup across all player characters.

**Comment by anthonyronda** [comment]
I think I followed your reproduction instructions correctly, but I was unfortunately not able to reproduce this error.

Mind sharing your technical details?
Operating System:
Browser:
Foundry Version:

**Comment by NachoTeller** [comment]
The same thing happens to me too and from what I've seen on Foundry VTT's Discord it's a general bug.

From the inventory, each object has some cells to quickly write the quantities, without the need to edit by opening the object, that is where the error occurs. The only way to modify the quantities and save them is to open the object's sheet and edit it there.

**Comment by anthonyronda** [comment]
Ok thanks, I do not typically edit that field in the Actor sheet. Reproduced the bug and looking to resolve this for the next release
