### ISSUE TITLE
Can't install the module

### ISSUE THREAD

**Issue by Escherjem** [vttred/ose#126]
This module doesn't show up on the module list in Foundry. The manifest link won't work either, and returns an error message.

_Installation failed: The "path" argument must be of type string. Received undefined_

**Comment by anthonyronda** [comment]
Are you in the module installation window? This is a game system, not a module.

If you currently have the module install window open, please take these steps.

1. Close Module Installation window.
1. Click the Game Systems tab.
1. Click the Install System button.
1. Proceed with installation.
