### ISSUE TITLE
Problems with Containers, only one at a time

### ISSUE THREAD

**Issue by NachoTeller** [vttred/ose#132]
In the Containers section, when you add a container, for example a backpack, it creates a new section called backpack. Up to that point everything works fine. The problem comes when you want to add a second container, for example a Coin Bag. If you drop it into the Containers category, it doesn't let you, it moves it directly into the backpack, counting as if it were in the backpack instead of as a separate container. In case you hit the "+" button directly and create it manually, it takes it out of the backpack and puts it into the Coin Bag.

Try to make sure that when you drop different containers they are placed in "Containers" or "inside an already created container" depending on where you drop it.

**Comment by NachoTeller** [comment]
Also note that now you can no longer sort objects by dragging them into the containers. If you try to sort them, they are taken out of the container and sent to Misc. or Treasures.

**Comment by anthonyronda** [comment]
Hello! Regarding your first paragraph, I can follow your instructions and I didn't encounter the behavior you're experiencing. I am definitely hearing several people finding the new Container display unintuitive, which might be why you can't find the behavior you want. 1.4.2 has a different layout that I think you'll find more intuitive.

> Try to make sure that when you drop different containers they are placed in "Containers" or "inside an already created container" depending on where you drop it.

Placing something from the sidebar directory into a container directly would be new behavior. I don't believe it ever worked that way. The Foundry API for dragging items within an actor and the API for dragging items from the sidebar to an actor are different, and we don't currently extend the "sidebar to actor" code to work with containers.

> Also note that now you can no longer sort objects by dragging them into the containers. If you try to sort them, they are taken out of the container and sent to Misc. or Treasures.

In 1.4.2 there is indeed no sorting by dragging items around inside containers.

**Comment by anthonyronda** [comment]
Checking in!

Are you still experiencing the behavior you encountered a couple weeks ago, or did the new container layout fix it?

**Comment by NachoTeller** [comment]
Good evening! I was able to test it today and it is now working properly, great job!
