### ISSUE TITLE
List of items arranged alphabetically

### ISSUE THREAD

**Issue by RJ1974** [vttred/ose#137]
Hello Development Team,

how are you? I'm new to Foundry VTT, I'm still just a gamer and I'd like to ask for your guidance. On a table I play OSE (using its Old School Essentials module), we have a problem. That is, the list of items is not organized in alphabetical order, is there any way to implement this possibility at the table we are playing? If yes, can you guide me where to find subsidies to perform such a task?

I thank you in advance for your attention to this one and I look forward to it.

**Comment by HerrSquash** [comment]
I see this is quite an old post, but by "list of items" do you mean in the character sheet or in the Items Directory? I'm not sure about the character sheet, but if you right click a folder in the Items Directory, you can choose to sort alphabetically or manually.

**Comment by anthonyronda** [comment]
We will close this issue as "didn't receive followup info" but we've just posed a question to our users regarding how to move forward with ordering on character and monster sheets. Please chime in!

See #398 for the discussion
