### ISSUE TITLE
Incongruence between Encumbrance and Movement Rate

### ISSUE THREAD

**Issue by IGALEGOI** [vttred/ose#159]
The judge at my table reported something unusual when looking at the weight ratio and movement rate, so I'm here to ask. Wouldn't the value be **+1** to the **value** determined in the table?

![Encumbrence](https://user-images.githubusercontent.com/97805442/161384967-ff389cdb-2ad6-4a25-b334-b368495268d7.png)

I did some tests here, and it doesn't seem to be following the table. 

![Test Encumbrence 1](https://user-images.githubusercontent.com/97805442/161385004-cfb0c59e-fc18-4f44-afa0-700b98db66eb.png)

![Test Encumbrence 2](https://user-images.githubusercontent.com/97805442/161385010-32004247-b33f-45d5-8a30-1220f59814d4.png)

Can someone check this out, I believe it is something to be fixed.

**Comment by anthonyronda** [comment]
Off by one! Nice catch
