### ISSUE TITLE
Character sheet not displaying properly and unable to update modules running

### ISSUE THREAD

**Issue by leagueoffoundryvttdevs** [vttred/ose#167]
**Submitted By**: Orcwart
**Feedback Type**: Bug
 
**Core:** 9.268
**System:** ose v1.4.5
**Module Version:** ose v1.4.5
 
**Description**:
Hi. I upgraded Foundry to 9.268 and have the latest OSE game system installed. I found that OSE character sheets now display weirdly, in that they display a list of items, spells etc, and no ability scores.

I thought there might be a conflict with a module and tried to deactivate them all, but clicking on Save Module Settings had no effect. Also, clicking on Return to Setup in the Settings pane also had no effect.

Hope this helps.<details>
<summary>Active Modules</summary>

about-time--v1.0.6;
actually-private-rolls--v1.0.0.2;
ambientdoors--v2.2.6;
animated-spell-effects--v0.6.8;
animated-spell-effects-cartoon--v0.1.9;
ATL--v0.4.0;
autoanimations--v3.1.2;
autocomplete-whisper--v0.3.4;
BatchPermissionsByFolder--v0.0.2;
bug-reporter--v1.3.3;
calendar-weather--v3.1.7;
chat-notifications--v1.2.3;
chat-portrait--v0.6.4;
combat-utility-belt--v1.8.4;
combatbooster--v2.3;
compendium-folders--v2.4.3;
Custom-Token-Animations--v0.2.7;
cycle-token-stack--v0.5.4;
dae--v0.10.08;
dice-calculator--v1.5.1;
dice-so-nice--v4.5.0;
foundryvtt-simple-calendar--vv1.3.75;
fudge--v1.1.1;
fxmaster--v2.4.0;
gm-screen--v3.0.1;
JB2A_DnD5e--v0.4.0.02;
lib-changelogs--v0.7.7;
lib-wrapper--v1.12.4.0;
manny-language--v1.0.3;
nice-more-dice--v1.1.0;
no-summon-vision--v1.0.0;
ose-content--v0.5.1;
perfect-vision--v3.7.33;
permission_viewer--v0.9.3;
pings--v1.3.0;
sequencer--v2.0.16;
settings-extender--v1.2.0;
SharedData--v1.0.0;
simple-dice-roller--v1.3.5;
socketlib--v1.0.10;
token-animation-tools--v1.2.1.0;
torch--v1.4.4;
turnAlert--v2.0.0;
</details><details>
<summary>Additional Details</summary>

undefined
</details>

**Comment by anthonyronda** [comment]
After consulting with the user, we determined that module Manny's Languages had produced this error.
