### ISSUE TITLE
Tips for design system and typography

### ISSUE THREAD

**Issue by narukaioh** [vttred/ose#179]
I'm making a series of system style modifications in my foundry. To leave with some of the typography of the book.

Is there a big problem to be able to create a theme based on the style of the books?

I researched the sources of the book and saw that many are paid...
![Screen Shot 2022-05-08 at 15 08 25](https://user-images.githubusercontent.com/359991/167309453-b96b3efb-1f1a-4203-80e3-70c725ce6dd7.png)

I'm still working on the changes, but the fonts are only installed on my machine...

**Comment by anthonyronda** [comment]
While we have requested and received a special exception to the Third Party Trademark License to allow the name Old-School Essentials in the title of the system package, we do not have permission to use the trade dress. Trade dress is called Product Identity by the Open Game License, and as such is not licensed for use, and is explicitly not allowed by the Third Party Trademark License.

**Comment by anthonyronda** [comment]
You're free to do as you like on your own. I recommend the Custom Fonts and Custom CSS modules to spruce up your Foundry instance. Unfortunately we won't be accepting it as a pull request. We want to be completely open source!

I'm going to close this issue now, but feel free to add any other questions you have about this.

**Comment by narukaioh** [comment]
> You're free to do as you like on your own. I recommend the Custom Fonts and Custom CSS modules to spruce up your Foundry instance. Unfortunately we won't be accepting it as a pull request. We want to be completely open source!
> 
> I'm going to close this issue now, but feel free to add any other questions you have about this.

Thank you so much!
