### ISSUE TITLE
Default token settings do not work

### ISSUE THREAD

**Issue by JordanRR** [vttred/ose#186]
The default token settings do not work. whether I drag and drop or import from compendium. Display name is Never Displayed (default should be hovered by anyone), Vision is 0/0 (should be 60/30), and display bars are Never diplayed (should be hovered by anyone) and None/None (should be hp and aac.value). 

I did deactivate all modules (but kept Find The Culprit, which was used to deactivates all modules), and the issue persists. I do not know if the problem is from core foundry or OSE, though.

Thanks!

**Comment by JordanRR** [comment]
Well, I just installed Twodsix and checked... Problem is still there. I suppose it's not an issue with OSE. Sorry for the bother!

**Comment by anthonyronda** [comment]
You may double-check with Foundry Support or Official Foundry Discord Helpers for guidance, but my current understanding is that those settings, Never Displayed, 0/0, and Never Displayed respectively, are Foundry VTT defaults (at least in V9.269). You may be used to a game system that changes the default behavior

**Comment by JordanRR** [comment]
Thank you, Anthony. I use the OSE Compendium. I don't know if the way it works changed or if I use to modify the settings each time, but it was a problem for me only recently. Do you know how I can change the default behavior myself?
