### ISSUE TITLE
[Bug] HD roll does not calculate CON modifier correctly

### ISSUE THREAD

**Issue by JordanRR** [vttred/ose#195]
On a PC sheet, when you click the HD button, the CON modifier is applied only once instead of once per hit dice (max 9 times). 

Thank you!

**Comment by anthonyronda** [comment]
I did have a discussion about this with another code contributor. I decided that in the short term we can have the current roll output apply the CON modifier multiplied by the level, with a max of 9

There may be a need later on for a custom chat card that clearly labels the roll's purpose, how the modifier was calculated, a button to apply the new max hp, etc. We'd treat that as an enhancement request

**Comment by JordanRR** [comment]
Excellent, thank you!

**Comment by anthonyronda** [comment]
#269 fixes the bug, sorry for the long wait for what turns out to be a 1-line fix!

Keep an eye out for #270, an enhancement request for a more automated hp level up feature
