### ISSUE TITLE
Character sheet issue with PopOut!

### ISSUE THREAD

**Issue by JordanRR** [vttred/ose#197]
When we use the PopOut! module to put a character sheet in its own window, we lose the tabs on the right, making the sheet mostly unusable. 

Thanks!

**Comment by anthonyronda** [comment]
It has been without progress while I take care of other tasks for a while now, but this particular issue will smooth itself out with the new character sheet redesign in #97 

I will keep this open until that has been completed. Until then I won't be taking action on this

**Comment by JordanRR** [comment]
No problem, thank you for your hard work!

**Comment by JordanRR** [comment]
> If you check Bounding Box Compatibility Mode in the PopOut Settings the sheets should work properly. ![](https://camo.githubusercontent.com/8a47a65a1bba8feb470a2066c62a4e529397b1fc86e38939970709cf791edfe3/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3935353939303437353930353539333431362f3938373137333634393333393533313330342f53656c656374696f6e5f3634362e706e67) Snapshot courtesy of P. Troilus. Note: This is a client-side setting so each player will need to check it or you will need to Socket Sync it.

Yes, it works! Thank you!

**Comment by anthonyronda** [comment]
Just closing this out, as the planned fix is "entirely new character sheet design"
