### ISSUE TITLE
Can't create characters since last update.

### ISSUE THREAD

**Issue by oheilo** [vttred/ose#217]
### What happened?

After rolling for stats they don't appear on the character sheet, which also looks weird, lacking the hp box borders. Most boxes says 0 and the ones in the middle of the sheet, MEL, MIS Ov and En displays "NaN".

### What is the expected behaviour?

Being able to create characters.

### Foundry VTT Core Version

V9

### Old-School Essentials Core Version

1.6.0

### Please update your browser regularly. Which (updated) browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anthonyronda** [comment]
@oheilo please uninstall ose 1.6.0 and reinstall ose 1.5.1.

Due to a process error, 1.6.0 was temporarily available on V9 for a short time. 1.6.0 is not compatible with Foundry VTT V9
