### ISSUE TITLE
Abilities/Attacks/Spells do not print to chat.

### ISSUE THREAD

**Issue by justinthejaguar** [vttred/ose#219]
### What happened?

1. Create an ability for an actor.
2. Add a macro into the the ability. Example: "[[4d6]]"
3. Click the show icon for the ability.
4. Nothing appears in the chat.

### What is the expected behaviour?

The ability should print the result of a 4d6 roll to chat.

### Relevant Errors and Warnings

```shell
Expanding the New Ability shows "[object Promise]"
```

### Additional Support Details

Foundry VTT 10.284; OSE 1.6.2; Mac OS 12.5.1 M1; Electron app and browser.
![Screen Shot 2022-09-02 at 7 32 11 PM](https://user-images.githubusercontent.com/38022481/188246655-136b7070-c321-4507-80f4-018acad7f25d.png)
![Screen Shot 2022-09-02 at 7 32 23 PM](https://user-images.githubusercontent.com/38022481/188246657-4038d30d-0d92-4bfa-8f0c-d5b6157a01f4.png)

### Foundry VTT Core Version

V10

### Old-School Essentials Core Version

1.6.2

### Please update your browser regularly. Which (updated) browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anthonyronda** [comment]
Thanks for the report. There's a new method for "enriching HTML" that isn't being applied in either the chat context or the item summary context

**Comment by anthonyronda** [comment]
The enriched HTML change was the fix
