### ISSUE TITLE
Type: Item Descriptions are not appearing

### ISSUE THREAD

**Issue by justinthejaguar** [vttred/ose#231]
### What happened?

1. Create Item
2. Type Item "Sample"
4. Edit item description.
5. Save.
6. Description disappears.

### What is the expected behaviour?

The item description should appear on the item after saving.

### Relevant Errors and Warnings

```shell
None listed. The description simply disappears. I imagine this is likely due to the new way this data is accessed.
```

### Additional Support Details

Foundry 10.285
OSE 1.6.3
Chrome
Mac OS M1 Monterey 12.5.1

### Foundry VTT Core Version

V10

### Old-School Essentials Core Version

1.6.3

### Please update your browser regularly. Which (updated) browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by justinthejaguar** [comment]
There appears to be another issue with the item sheet. Updating the 'slow' checkbox with a check disappears after closing the sheet and saving information. Issue was brought to attention by BuzzardB#7495 9/21/22.

**Comment by Thronewolf** [comment]
I'm also experiencing this issue. It is only for regular "Item" types. This issue does not extend to "Weapon", "Armour", "Container", etc types of items. The description exists since when I go to edit the description field the text appears. But when the item is saved or viewed, the description text is not displayed.

Foundry: 10.286
OSE: 1.6.4
Firefox 105.01
Windows 10 21H2

Browser: Firefox

**Comment by justinthejaguar** [comment]
This issue extends to Ability Items as well.

**Comment by justinthejaguar** [comment]
This is a test of manually created items in the OSE 1.6.6 system both in the pane and on the character sheet. Container have the same problem spells were having due to typos in the html file.

Updates for the file from RabidOwlbear:
Line 1: {{#if (isV10)}}
Line 60:         owner=owner editable=editable async=true}}

**Item**: Creating in the item pane and the character sheet is possible. After saving the item information in the sheet, you are unable to see the text. Item information **does not** appear when expanded in the actor sheet. This extends to treasures
**Weapon**: Creating in the item pane and the character sheet is possible. After saving the item information in the item sheet, you are unable to see the text. It appears when expanded on the actor.
**Armor**: Creating in the item pane and the character sheet is possible. After saving the item information in the item sheet, you are unable to see the text. It appears when expanded on the actor.
**Spell**: Creating in the item pane and the character sheet is possible. After saving the item information in the item sheet, you are unable to see the text. It appears when expanded on the actor.
**Ability**: Creating in the item pane and the character sheet is possible. After saving the item information in the item sheet, you are unable to see the text. It appears when expanded on the actor.
**Container**: Unable to open a created container at this time.

**Comment by wyrmisis** [comment]
Is anyone working on this? If not, I can pick it up.
