### ISSUE TITLE
Evaluate sunsetting support for Foundry v9

### ISSUE THREAD

**Issue by wyrmisis** [vttred/ose#251]
### New Feature or Changed Behaviour

Per [discussion](https://discord.com/channels/929420928528568390/929511321488203819/1028293995698335806) in Discord, as Foundry v10 and the module ecosystem around it become more stable, it may be worth considering ending support for v9 in the codebase.

### Why?

The codebase currently features a good number of deprecation warnings (see #211), and many would-be warnings are suppressed by duplicate code that's there to maintain support for Foundry v9. More code = more bugs.

Additionally, there are a few handy code splitting options available to us in v10 that make it easier to localize custom data handling and functionality for specific types of item or actor (e.g.: computed values).

Lastly, v9-specific code is marked for eventual removal anyways; the longer we wait and the more stuff we add before that point, the harder ripping it out is going to be.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anthonyronda** [comment]
Thanks for making an issue for discussion. We held our discussion in the Discord server here

https://discord.com/channels/929420928528568390/929511321488203819/1028292180730716240

and here

https://discord.com/channels/929420928528568390/929511321488203819/1029828719524728883

In short, we heard a consensus in favor of removing existing code which sacrifices readability for V9-V10 cross-compatible support, leaving V10 support in place moving forward

People are free to continue discussing in this issue or Discord, but at the moment we will move forward and track the changes in #261
