### ISSUE TITLE
Add a gold cost column and total cost row to inventory table

### ISSUE THREAD

**Issue by IGALEGOI** [vttred/ose#26]
1. I recommend **adding a new cost icon** on all tabs, or some way to get the total.This will help make it easier to calculate the gold spent on character creation, and save a lot of time.

2. ***See issue #89 for tracking of this request.*** It would be good to add the **equip button for all items**, that allows you to change the state of equipped or not, changing the weight value. So you don't have to erase an item to decrease the weight. **PS.** The items in the container must be grouped together and deducted from the total weight, if unequipped or equipped.

![image](https://user-images.githubusercontent.com/97805442/149636671-c0296dd5-41f6-4925-ac08-702e28c4e538.png)

3. ***See issue #89 for tracking of this request*** **Improve the equip icon** by allowing it to select the options: Not Carried, Carried and Equipped. This can be done through the same selectable button. Which alternates its status among the three possible ones. 

![image](https://user-images.githubusercontent.com/97805442/149637331-9c61c331-bc22-4b10-b596-3bc2a96620ca.png)

4. ***See issue #90 for tracking of this request*** Add the **armor bonus option**. 
It allows you to separate the way the bonus is applied, and used on magic items such as rings or armor +1/2/3.

![image](https://user-images.githubusercontent.com/97805442/149638351-7d074869-bcaa-435e-a582-ea7ea20d9ce9.png)

**Comment by engleback** [comment]
You could create a container of weight zero and call it "Stash" and put all not carried items in there?

**Comment by IGALEGOI** [comment]
> 
It doesn't seem to work, and I also noticed a bug in relation to setting the weight of the items. Where I informed weight 100, but is computing 80.

![image](https://user-images.githubusercontent.com/97805442/150167306-f45c0fa6-31a9-424e-b17e-0e851a4a8a69.png)

**Comment by IGALEGOI** [comment]
> You could create a container of weight zero and call it "Stash" and put all not carried items in there?

It seems that if you use the **detailed weight rule** rather than the standard, you can determine the weight by yourself. So you can put X items in the container, and in it you can determine the overall weight, or item by item.

**Comment by anthonyronda** [comment]
Multipoint issues like this are not conducive to proper issue tracking. In the interest of curating our workspace, I'm going to make new issues for points 2&3, and point 4. I'm going to change the title of this to reflect the enhancement request of point number 1.

1. In the meantime, I highly recommend RabidOwlbear's OSE Item Shop (search Google). Of course, "use a module" is not a final answer to the usage concern you're having. However, I'd like to loop in a UX designer before making this sweeping change. One alternative for now might be to place it in the Modifiers dialog box. It's not really meant to for this purpose, but it's tucked away.

<img width="481" alt="image" src="https://user-images.githubusercontent.com/1410433/154122752-452cbf1e-edfd-4bd7-9a87-4375b1fc6450.png">

A related option would be to add a button next to the Modifiers button, and give the inventory list and the item total cost there.

Both of these suggestions are to temporarily alleviate your issue while we continue to overhaul the sheet design.

Points 2, 3, and 4. See the other issues linked below.

**Comment by anthonyronda** [comment]
@IGALEGOI after some discussion with the other contributors, I think I've decided that I'd prefer to put an icon button in the black bar that appears underneath the profile picture when you hover over it. When you click it, you will be shown how much your total inventory costs, and you can click a button to deduct your gp cost if you have enough. Mind you that it will only support gp, because that's what players get during SRD-only character creation and that's the price all SRD items are listed in.

My reason for not putting a gold cost column in the inventory screen is that you haven't raised a use case for it to be used during play, and it will contribute to visual clutter. We also can't support showing all currencies in the inventory item row, which may be more important for some games than it is for others.

The most fun solution for shopping will still be OSR Item Shop, but something minimal like this should be a great option.

**Comment by IGALEGOI** [comment]
@anthonyronda It will already be of great help. Especially in character creation, where most of the time is lost in creating the character sheet. No more spending time adding item by item, so now you just see the amount spent and deduct the value. 

Then we just have to play.

**Comment by anthonyronda** [comment]
This took much longer than I expected but changes in #169 were needed before I could complete development on this. Expect this feature to be completed this week
