### ISSUE TITLE
Enforce linting

### ISSUE THREAD

**Issue by anthonyronda** [vttred/ose#266]
What: A linter is a tool designed to help maintain a uniform code style according to maintainer-configurable settings. Enforcing linting is achievable in JavaScript projects using IDE plugins

Why: style differences reduce code readability and increase the possibility of bugs. when some people use linters and others don't you will more likely introduce many extra lines of changes in a commit, making code harder to review

Referenced:

        We should def consider linting for this kind of stylistic difference stuff.

_Originally posted by @wyrmisis in https://github.com/vttred/ose/pull/262#discussion_r1006238898_

**Comment by wyrmisis** [comment]
I'll hop on this once #262 and #263 are in. In the meantime, I think we should work out what linting rules we want to use. Anyone have a favorite bundle of presets?

Some tooling that could help out with linting/formatting:
* [Stylelint](https://github.com/stylelint/stylelint) for our SCSS files
* [Prettier](https://prettier.io/) and [`pretty-quick`](https://github.com/azz/pretty-quick) for formatting code 
* [Husky](https://typicode.github.io/husky/#/) to run linting/formatting on commit (and block commits that fail linting)

**Comment by anthonyronda** [comment]
This technically should have been closed with the PR getting merged.

We have a number of linting rule warnings and errors, but I believe we can track that separately from this issue (creating one now, and linking this one there)

Husky was not added, but I think we can address that when we're ready for it
