### ISSUE TITLE
FoundryVTT macro bug

### ISSUE THREAD

**Issue by Kukrapuff** [vttred/ose#277]
### What happened?

Whenever I try to create a macro with a magic item unlocked in the "Items" folder by my DM, it seems to fail. 

### What is the expected behaviour?

The macro should allow me to use the attack without the need to open the character's inventory

### Relevant Errors and Warnings

```shell
![image](https://user-images.githubusercontent.com/120993207/208325580-db9c01b1-4855-42c1-8440-1cd5cf3d45c9.png)
```

### Foundry VTT Core Version

V10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anthonyronda** [comment]
Yes, I noticed this recently while testing out some unrelated code fixes. I haven't reported it yet though, thanks for your report!

I have one or two leads to follow, hopefully this will be an easy fix

**Comment by anthonyronda** [comment]
The error lies in the "drag-and-drop to the macro bar" code, probably needs to be changed to using uuid like previous drag and drop fixes
