### ISSUE TITLE
Character Sheet shows Descending AC even when Ascending AC is selected

### ISSUE THREAD

**Issue by lonpalmer** [vttred/ose#288]
### What happened?

Create a character with the Ascending AC option checked in configuration.
Equip Armor
Notice the Attributes page only shows the descending AC not the Ascending AC.

### What is the expected behaviour?

Ascending AC should be shown on the character sheet when selected in configuration.

### Relevant Errors and Warnings

```shell
No Errors or warnings
```

### Additional Support Details

Foundry VTT 10 Build 291
Old-School Essentials Plugin Version 1.7.1

### Foundry VTT Core Version

V10

### Old-School Essentials Core Version

1.7.1

### Please update your browser regularly. Which (updated) browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wyrmisis** [comment]
@lonpalmer This should be resolved in the linked PR.
