### ISSUE TITLE
Attributes tab not displaying items added by the + button (Monster character sheet)

### ISSUE THREAD

**Issue by Gunterv1** [vttred/ose#290]
### What happened?

Adding the "item" from the "+" button on Attributes tab of the monster character sheet sends it to the Inventory tab. 
Added "items" do not display on the Attributes tab under the "+" button.

![image](https://user-images.githubusercontent.com/122548660/212114716-f471cc4b-a6e5-40c6-bc5b-f53622fdb7bd.png)
![image](https://user-images.githubusercontent.com/122548660/212114861-0da34473-b3a8-4a25-acf5-5019273bad36.png)
![image](https://user-images.githubusercontent.com/122548660/212114975-42714315-47a5-41ba-ba64-bf4af0e303cf.png)

### What is the expected behaviour?

- clicking the + button on the Attributes tab gives a choice to add abilites or weapons to the abilities and weapons view (adding the item to the monster)
- actual behavior: gives a choice to add any item type, but will only display the added item if it's an ability or weapon

### Foundry VTT Core Version

V10

### Old-School Essentials Core Version

1.7.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bakbakbakbakbak** [comment]
The current behavior will only display items of type weapon, or if the item is rollable, which an item isn't by default. So the two solution alternatives seems to be:

1. Open up to have any item, rollable or not, which would include added both `item` and `armor`.
2. Remove the options to add `item` and `armor`.

monster-attributes-tab.html row 91: `data-choices="weapon,ability,armor,item"><i class="fas fa-plus"></i></a>`
monster-attributes-tab.html row 100: `<li class="item-entry item {{#if (or item.system.roll (eq item.type 'weapon'))}}item-rollable{{/if}}"`
