### ISSUE TITLE
Catalan translation

### ISSUE THREAD

**Issue by adn770** [vttred/ose#293]
### New Feature or Changed Behaviour

I'd like to contribute with a Catalan translation that I'd added to the crowdin project.

### Why?

There's an active community of players in our region and I'd like be able to use this module in our mother tongue. In particular for my own young daughters.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anthonyronda** [comment]
Hi! Thanks for your contribution! Your translations are added to #300, and the manifest config for adding Catalan as a new language is added in #301. These will get merged in 1.8.0, expected next week

**Comment by anthonyronda** [comment]
@all-contributors please add @adn770 for translation
