### ISSUE TITLE
Monsters don't show container contents

### ISSUE THREAD

**Issue by crazyclausewitz** [vttred/ose#31]
If you put an item into a container that is owned by a monster, the item vanishes. The data structure still holds it, but it is not displayed.

**Comment by freohr** [comment]
I can reproduce it. I'll see what I can do about it :)

**Comment by engleback** [comment]
working for me, I can create a container on a monster and drag a treasure to it, this only shows in the inventory tab though.

**Comment by anthonyronda** [comment]
@freohr I also can't reproduce. @crazyclausewitz could this have been related to #33 ?

**Comment by crazyclausewitz** [comment]
Currently I cannot reproduce it either. It may have vanished with the upgrade to Foundry version 9.
@anthonyronda : It was definitely not related to #33 as I only used items already showing on the monsters inventory sheet. However, I remember that one of the bugs I reported only showed up 99% of the time. It may well be that it was this one.

**Comment by anthonyronda** [comment]
Closing. If it shows up again try to find a console error, exact reproduction steps, or console log the contents of the monster's data.items
