### ISSUE TITLE
Existing Containers prior to 1.7.4 with Contents Will Not Delete

### ISSUE THREAD

**Issue by justinthejaguar** [vttred/ose#310]
### What happened?

1. Import a Container item from prior to 1.7.4 (github does not support json filetype, but will provide on request.)
2. Add the container to a character sheet.
3. Add items to the container.
4. Attempt to delete - this will fail if you select 'yes'
5. Clear items out of container - this will fail if you select 'yes'

### What is the expected behaviour?

The container should delete.

### Additional Support Details

M1 Mac Electron version

### Foundry VTT Core Version

V10

### Old-School Essentials Core Version

1.7.4

### Please update your browser regularly. Which (updated) browsers are you seeing the problem on?

Other

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xanstin** [comment]
I have this issue as well

**Comment by anthonyronda** [comment]
We'll revisit this after 1.8.0 because bakbak has a number of reworks for that release

**Comment by anthonyronda** [comment]
Fixed in #396
