### ISSUE TITLE
Issue with encumbrance thresholds for Move speed changes

### ISSUE THREAD

**Issue by Vilify-13** [vttred/ose#315]
### What happened?

When adding equipment to a character sheet(tested with fresh game+no modules installed), encumbrance thresholds are not set properly. See the attached video for steps to reproduce.

https://user-images.githubusercontent.com/109003055/213953111-0d2410dd-7f7d-4784-b16f-b13acacec267.mp4

Thresholds seem to be set to the following while detailed or complete encumbrance is enabled:
Up to 199 coins=120' (40')
Up to 399 coins=90' (30')
Up to 799 coins=60' (20')
up to 1600 coins=30' (10')

The correct values should be the following:
Up to 400 coins= 120' (40')
Up to 600 coins= 90' (30')
Up to 800 coins= 60' (20')
Up to 1600 coins= 30' (10')

### What is the expected behaviour?

Expected behavior should have values 1 over the threshold be for the expected move values, 

0 to 400 coins= 120' (40')
401 to 600 coins= 90' (30')
601 to 800 coins= 60' (20')
801 to 1600 coins= 30' (10')

### Foundry VTT Core Version

V10

### Old-School Essentials Core Version

1.7.4

### Please update your browser regularly. Which (updated) browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anthonyronda** [comment]
fixing now. For what it's worth 400.1, 600.1, 800.1, and 1600.1 will be encumbered at the next highest level since we allow floating point numbers
