### ISSUE TITLE
Create migration for documents without default icons

### ISSUE THREAD

**Issue by crazyclausewitz** [vttred/ose#32]
I was browsing through my monster list and noticed that most of the ability and weapon icons have been replaced by 'icons/svg/item-bag.svg'. When looking at my actors.db, I can see that these abilities and weapons don't have an 'img' entry. I guess in earlier versions the 'img' entry was only added when the icon had been changed and a default icon was provided for items with empty 'img' entries. Looks like this has been lost along the way.

**Comment by engleback** [comment]
The monster list is part of the compendium which is another module I think

**Comment by justinthejaguar** [comment]
https://github.com/vttred/ose-content

**Comment by anthonyronda** [comment]
It's true that some unused bits of code still reference `icons/svg/` image assets, but I don't think they're actually used. There's a separate assets directory that hosts all of the current "default icons."

Have you encountered broken image refs for `icons/svg/` ("NOT FOUND" errors)? I'd want to know about that here

**Comment by crazyclausewitz** [comment]
I build my monster database long before there was a compendium, which is why most of my monsters don't have an img entry. The img entry was introduced fairly late into the codebase and it seems to only get added to the database if the icon is actually changed. Before that, the behavior was to provide default icons for weapons and abilities. But this code has been lost in the editing.
Right now there is no code for handling monsters without an img entry, which is why the foundry default fallback (bag icon) is shown. I have no way of adding the img entry to the database short of changing every single icon for hundreds of monsters.

**Comment by engleback** [comment]
Are we maintaining the compendium as well?

**Comment by anthonyronda** [comment]
@crazyclausewitz could you tell us the expected behavior you want?

@engleback as Justin referred to above, there's a new repository for the OGL compendium but I have not begun to make changes to it. The last U~man release is still the latest release

**Comment by crazyclausewitz** [comment]
If a weapon, ability, armor, spell or item has no 'img' entry add one and set it to the default icon for that category (i.e. systems/ose/assets/default/weapon.png, systems/ose/assets/default/ability.png, systems/ose/assets/default/armor.png, systems/ose/assets/default/spell.png and systems/ose/assets/default/item.png)
Maybe put it into _prepareItem on the actor sheets.

**Comment by anthonyronda** [comment]
We recommend the following macro for each of your compendiums (contributed by @RabidOwlbear)
```js
let compendiumName = "YOURCOMPENDIUMNAME";

function defaultIcons() {
  return {
    spell: "systems/ose/assets/default/spell.png",
    ability: "systems/ose/assets/default/ability.png",
    armor: "systems/ose/assets/default/armor.png",
    weapon: "systems/ose/assets/default/weapon.png",
    item: "systems/ose/assets/default/item.png",
    container: "systems/ose/assets/default/bag.png",
  };
}

let pack = game.packs.get(compendiumName);
pack.map((actor) => {
  const items = actor.items;
  items.map(async (item) => {
    if (item.img === null) {
      await item.update({ img: defaultIcons()[item.type] });
    }
  });
});
```

And the following macro for items on the actors already in your world (run once)

```js
function defaultIcons() {
  return {
    spell: "systems/ose/assets/default/spell.png",
    ability: "systems/ose/assets/default/ability.png",
    armor: "systems/ose/assets/default/armor.png",
    weapon: "systems/ose/assets/default/weapon.png",
    item: "systems/ose/assets/default/item.png",
    container: "systems/ose/assets/default/bag.png",
  };
}

game.actors.map((actor) => {
  const itemsData = actor.data.items;
  itemsData.map(async (item) => {
    if (item.img === null) {
      await item.update( { img: defaultIcons()[item.type] } );
    }
  });
});
```

These only gives items with missing pictures a new default picture

**Comment by RabidOwlbear** [comment]
The compendiumName variable has a minor caveat. If the compendium is a world compendium, as in not one included with a module, the value will be 'world.YOURCOMPENDIUMNAME' otherwise it will be the module name found in the parenthesis below the compendium name like this 'module-name.YOURCOMPENDIUMNAME'

**Comment by crazyclausewitz** [comment]
Thanks for the macros! I think they will work for me for now.
But the point I'm making is that you actually need some function to update user compendiums. As soon as the underlying data structures change, everyone with custom assets will again be stranded with outdated and potentially troublesome data structures.

**Comment by anthonyronda** [comment]
@bakbakbakbakbak and @wyrmisis regarding our previous discussions about migrations, do actor/token `img` migrations like above also belong in their respective data models?

**Comment by bakbakbakbakbak** [comment]
> @bakbakbakbakbak and @wyrmisis regarding our previous discussions about migrations, do actor/token/item `img` migrations like above also belong in their respective data models?

Yes, we can do this migration from the data models for this. I've created a pull request: #322

**Comment by anthonyronda** [comment]
Will be in the upcoming 1.8.0 release
