### ISSUE TITLE
Attack Fails with No Target

### ISSUE THREAD

**Issue by justinthejaguar** [vttred/ose#333]
### What happened?

1. Create an actor with a weapon
2. Roll attacks with no target.
3. If the attack is 1 or less the attack fails.

### What is the expected behaviour?

The attack roll should always occur regardless of the roll result to hit if there is not a target. The only possible exception would be a 1, which RAW always misses. I propose that this still result in a damage roll with no target, as there is no alternative way for the GM/Players to create a weapon damage roll in chat without a to hit roll preceding it.

### Relevant Errors and Warnings

```shell
N/A
```

### Foundry VTT Core Version

V10

### Old-School Essentials Core Version

1.7.5

### Please update your browser regularly. Which (updated) browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anthonyronda** [comment]
As @bakbakbakbakbak mentions in #332, do we consider this a bug or an enhancement? I'm not sure if I'm misunderstanding, but I think it's generally working as designed and is according to RAW, but we want to design for another type of need.

If you agree that #332's suggestion is a better approach to your issue, maybe we can close this one? :)

**Comment by justinthejaguar** [comment]
I think 332 works fine.
