### ISSUE TITLE
Individual Initiative/Reroll Each Round is not working.

### ISSUE THREAD

**Issue by superpcm** [vttred/ose#338]
### What happened?

1. In the OSE Settings, select "Individual initiative" and "Reroll each round".
![image](https://user-images.githubusercontent.com/70666425/217003114-6a215d0b-90aa-43b1-9874-4b2eb6a63374.png)

2. Place two tokens on a map and enter them into combat.
![image](https://user-images.githubusercontent.com/70666425/217003668-f1edb68d-2585-48f7-bbb2-50b74ebaa6da.png)

3. Initial initiative will roll and be presented correctly.
![image](https://user-images.githubusercontent.com/70666425/217083488-7ba50922-80de-4803-895e-902282cd4f46.png)

4. Advance to the next round. Initiative stays the same, no new roll is made for any combatants.
![image](https://user-images.githubusercontent.com/70666425/217083586-ae553284-7035-4749-8005-6724b1b713aa.png)

5. This is the same for any round going forward, initiative does not change.
![image](https://user-images.githubusercontent.com/70666425/217083716-b39d0cfb-9ba4-45b7-bc96-f86632078e97.png)

**Performed on a new world with no modules enabled.**

### What is the expected behaviour?

Every round initiative should be randomized for all combat participants.

### Relevant Errors and Warnings

```shell
None.
```

### Foundry VTT Core Version

V10

### Old-School Essentials Core Version

1.7.5

### Please update your browser regularly. Which (updated) browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anthonyronda** [comment]
Fixed in #397
