### ISSUE TITLE
Container contains itself, then disappears

### ISSUE THREAD

**Issue by Deandls** [vttred/ose#357]
### What happened?

When moving a container to be placed inside itself, the container disappears leaving the encumbrance amount the same.

https://user-images.githubusercontent.com/126306600/221334556-38c3052e-e3a2-464e-8e75-298452ae2052.mp4

### What is the expected behaviour?

I expect the container to not be allowed to go inside itself.

### Relevant Errors and Warnings

```shell
No error or warning
```

### Additional Support Details

Foundry Virtual Tabletop: Version 10 Build 291
Old-School Essentials 1.7.6
Active Modules: 1

### Foundry VTT Core Version

V10

### Old-School Essentials Core Version

1.7.6

### Please update your browser regularly. Which (updated) browsers are you seeing the problem on?

Other

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bakbakbakbakbak** [comment]
Have confirmed the bug, and provided a fix for it. It does have to wait for a rather enormous pull request - so it may take a little while to be implemented.

**Comment by anthonyronda** [comment]
This was merged in #356 today but may take some additional time to make it to the system. We will likely have a 1.7.6 release this week, and this fix will be in 1.8.0 next week
