### ISSUE TITLE
v11: Unable to edit enrichedHTML fields

### ISSUE THREAD

**Issue by bakbakbakbakbak** [vttred/ose#363]
### What happened?

1. Open item / actor
2. Try to edit a description (rich HTML)

### What is the expected behaviour?

The editor should open, but it doesn't for some reason.

### Relevant Errors and Warnings

```shell
`tinymce.min.js:4 Uncaught (in promise) TypeError: e.split is not a function
    at zR (tinymce.min.js:4:359986)
    at tinymce.min.js:4:360859
    at qR (tinymce.min.js:4:361079)
    at tinymce.min.js:4:380473
    at new jA (tinymce.min.js:4:380493)
    at tinymce.min.js:4:403017
    at Array.<anonymous> (tinymce.min.js:4:403122)
    at Ne (tinymce.min.js:4:5303)
    at s (tinymce.min.js:4:402860)
    at ia.bind (tinymce.min.js:4:50411)`
```

### Additional Support Details

Foundry Virtual Tabletop: Version 11 Prototype 2, 11.293
Game System: ose-dev, AUTOMATICALLY REPLACED BY GITHUB WORKFLOW ACTION
Active Modules: 2
Performance Mode: 2

OS: Unknown
Client: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
GPU: ANGLE (AMD, AMD Radeon RX 590 Series (polaris10 LLVM 15.0.7), OpenGL 4.6)
Max Texture Size: 16384

No viewed scene

Actors: 2 | Items: 2 | Journal: 0 | Rollable Tables: 0 |
Playlists: 0 | Compendium Packs: 0 | Chat Messages: 0

### Foundry VTT Core Version

None

### Old-School Essentials Core Version

1.8.x

### Please update your browser regularly. Which (updated) browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anthonyronda** [comment]
I decided to add a new label for this ;)

I'm not seeing this on the current 1.8.x branch. Was there a fix for this in a recently merged PR of yours?

**Comment by anthonyronda** [comment]
I just saw the v11, my bad 😅 
Thanks for tracking this!

**Comment by anthonyronda** [comment]
I think this is out of our hands. Please try the following alternate reproduction steps:

1. Open a world in any game system.
2. Go to the Journals tab and create a new journal entry.
3. Create a new page of the Journal Entry and change the sheet for that page to TinyMCE and save changes
4. Attempt to edit the page of the Journal Entry (nothing happens, same console error)

Still present in V11dev2

**Comment by anthonyronda** [comment]
It's tracked here https://github.com/foundryvtt/foundryvtt/issues/9121
