### ISSUE TITLE
Resizable Item Windows

### ISSUE THREAD

**Issue by Deandls** [vttred/ose#364]
### New Feature or Changed Behaviour

Add the little resize window icon on item windows to allow players to resize item windows.

### Why?

This would make it possible for players or the Referee to change the window size to view item sheets with large images, long descriptions, or charts without having to scroll.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anthonyronda** [comment]
Yes I consider this an oversight–almost a bug but not quite–that makes me prioritize it over other enhancements
