### ISSUE TITLE
Save button on chat card

### ISSUE THREAD

**Issue by JhaelenTerear** [vttred/ose#370]
### What happened?

Save button in chat card message aren't active. Tried on an existing world with and without module, and on a new test world without anything than the system. No error or warning in the console.
![image](https://user-images.githubusercontent.com/58259514/226868930-4f6d5369-b601-4054-8f55-5fa3ef23f0a8.png)

### What is the expected behaviour?

The button should be active and roll the save for the selected token.

### Relevant Errors and Warnings

```shell
Nope, nothing in the console.
```

### Foundry VTT Core Version

V10

### Old-School Essentials Core Version

1.7.6

### Please update your browser regularly. Which (updated) browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anthonyronda** [comment]
We don't have a good label for chat card bugs. Triaged and hope to have a fix today
