### ISSUE TITLE
Encumbrance System is not updating

### ISSUE THREAD

**Issue by justinthejaguar** [vttred/ose#4]
Basic Encumbrance is not currently calculating correctly.

Basic Encumbrance is set
![image](https://user-images.githubusercontent.com/38022481/147882247-93c5edaa-84c9-4021-a227-2de89086132f.png)
Calculate Movement is checked in Character Sheet Tweaks
![image](https://user-images.githubusercontent.com/38022481/147882273-057c96fa-00eb-4263-8d8a-cbe6415dab7b.png)
Plate Armor is equipped
![image](https://user-images.githubusercontent.com/38022481/147882284-be02fefd-d8a1-4f37-ab45-194b7571c0fe.png)
Movement is not impacted
![image](https://user-images.githubusercontent.com/38022481/147882291-0287fafa-e4fe-4a21-a58c-679f0e41abce.png)
Rules on Encumbrance
![image](https://user-images.githubusercontent.com/38022481/147882327-335a5c47-ace9-4435-8f6c-7a5601c38e1a.png)
![image](https://user-images.githubusercontent.com/38022481/147882373-1ac7b867-77ae-4d59-9277-c7c928dbf27f.png)

**Comment by anthonyronda** [comment]
This has been closed as fixed. Thanks for reporting this!
