### ISSUE TITLE
Up-to-date foundry types for TSServer

### ISSUE THREAD

**Issue by freohr** [vttred/ose#41]
Can we add https://github.com/League-of-Foundry-Developers/foundry-vtt-types to the package list, and update the `tsconfig.json` appropriately? This should be linked with the effort to update the version of the other dependencies.

**Comment by anthonyronda** [comment]
As far as I can tell, none of the code benefits from typechecking at present, but this is planned for the future

**Comment by anthonyronda** [comment]
while I've deleted `tsconfig.json` for now, we'll put it back when we're ready to tackle typescript. I'm starting a GitHub project for typescript implementation
