### ISSUE TITLE
Clicking "Old School Guide" button from "Help & Documentation" opens empty window

### ISSUE THREAD

**Issue by r-valyar** [vttred/ose#414]
Clicking "Old School Guide" button from "Help & Documentation" opens empty window.
Screenshot attached

![image](https://user-images.githubusercontent.com/63558984/235099881-b3e4440c-dcec-4d45-93fb-2d0a080361e5.png)

**Comment by anthonyronda** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/1410433/235322699-6daab7bf-41a2-46d4-85d1-1f258d681462.png">
Works for me in Chrome and Firefox. Can you provide the copy/pastable details from the Support button?

You should probably also check if it works without modules installed

**Comment by r-valyar** [comment]
I created new world without any of the regular modules I use (left just Module Management + working) and when I clicked the button, indeed I was able to open the web page. Did some browsing in other tabs and when i was back to the Foundry, I got the same issue when I tried to open the page.

This is export from the JS console, I presume it might be due to uBlock origin and/or privacy policy that blocks 3rd party cookies.

Still, I can't explain why I opened it when the world was just created and can't subsequently. 

![image](https://user-images.githubusercontent.com/63558984/235337929-448a1cd7-c52e-4d7a-961d-2ebce5e290e0.png)

**Comment by anthonyronda** [comment]
those blocked cookies for ose.vtt.red shouldn't matter. The insecure request from foundryvtt.wiki is from clicking "Community Wiki Pages," not the Old School Guide button. If you clicked the community wiki and it resulted in an error, there could be a problem fetching other pages after that? Seems unlikely though

**Comment by anthonyronda** [comment]
I really can't investigate without full details since you haven't provided reproduction steps or browser/OS combination

**Comment by r-valyar** [comment]
I have this on Windows and Mac:
- MacOS Ventura 13.3.1 (22E261)
- Windows 10 2H22

Browser

**Comment by anthonyronda** [comment]
Here is how I would write reproduction steps after interpreting what you've written here:

1. Create new ose world
2. Go to Settings tab
3. Wait 10-30 minutes ("at some point it stops loading")
4. Click Old-School Guide

Unable to reproduce in Chrome 112 and ose 1.8.3

**Comment by r-valyar** [comment]
Apologies, I've seen now that I didn't specify the Browser, I copied the version and forgot the **Firefox**. 

I will be more precise next time I report a bug and instructions for reproducing it.

**Comment by r-valyar** [comment]
Issue seems to be resolved after one of the last updates. No longer facing blank window.
