### ISSUE TITLE
Allow GM/Referee to request saves and ability rolls from players

### ISSUE THREAD

**Issue by freohr** [vttred/ose#42]
I know there are other systems that allow GMs to request rolls from players, so maybe we can add the option to request saves and rolls from a character if a player is currently the owner of said character.

**Comment by IGALEGOI** [comment]
This functionality could be applied to the Party Overview, if you could select the icons present in the character. That would be good.  

![image](https://user-images.githubusercontent.com/97805442/150236892-d1c98da8-7117-4aab-b9ab-38367c746d20.png)

**PS.** I did the post #45 talking a little about this in Party Sheet -> Main.

**Comment by anthonyronda** [comment]
Implemented as Let Me Roll That For You support in #96, to be released Monday
