### ISSUE TITLE
Movement calculation for detailed and complete encumbrance broken

### ISSUE THREAD

**Issue by crazyclausewitz** [vttred/ose#447]
### What happened?

When playing with 'Detailed' or 'Complete' encumbrance the movement values are miscalulated once encumbrance reaches 401 coins.

For 401 coins Exploration movement shows 67.5 instead of 90. For 601 coins it is 30 instead of 60 and for 801 coins it is 7.5 instead of 30. Overland and encounter movement are off accordingly.

Looks like the calculation is done twice: 120 x 0.75 x 0.75=67.5.

### What is the expected behaviour?

Exploration movement should be 120, 90, 60 or 30.

### Additional Support Details

Foundry Virtual Tabletop: Version 11 Stable, 11.299
Game System: ose, 1.9.1
Active Modules: 0
Performance Mode: 0

OS: Unknown
Client: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
GPU: ANGLE (ATI Technologies Inc., AMD Radeon Pro 5300M OpenGL Engine, OpenGL 4.1)
Max Texture Size: 16384

Scene: 8400 x 4800 | Grid Size: 100 | Padding Percentage: 0.1
Walls: 0 | Ambient Lights: 0 | Ambient Sounds: 0 | Tiles: 108 | Tokens: 3

Actors: 598 | Items: 1058 | Journal Entries: 499 | Rollable Tables: 182 |
Playlists: 0 | Compendium Packs: 10 | Chat Messages: 2

### Foundry VTT Core Version

V11

### Old-School Essentials Core Version

1.9.1

### Please update your browser regularly. Which (updated) browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anthonyronda** [comment]
This was a very helpful issue, thanks! I think your clue may have lead @wyrmisis down the right track :D

**Comment by anthonyronda** [comment]
That said, please don't mind if I close as duplicate. We're tracking this in #446 and there's the PR in #450 which I plan to review very soon
