### ISSUE TITLE
1.9.3 Actor Bars not update

### ISSUE THREAD

**Issue by marcusadmortati** [vttred/ose#457]
### What happened?

With this update character resource bars can be set but cannot be saved when sheets are opened from the actors tab. They can only be saved from the token's open sheets on the canvas, which does not make the setting definitive, since in each canvas the bar must be reconfigured. Tested without mods activated.

### What is the expected behaviour?

The bars are set up correctly.

### Relevant Errors and Warnings

```shell
None.
```

### Additional Support Details

Foundry 11.300
OSE 1.9.3

### Foundry VTT Core Version

V11

### Old-School Essentials Core Version

1.9.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anthonyronda** [comment]
Good to hear :) thanks for reporting!
