### ISSUE TITLE
Secret descriptions are visible to players when editing the text of an item.

### ISSUE THREAD

**Issue by Naroek56** [vttred/ose#461]
Foundry Forge 10.291
OSE 1.8.6

Hi all,

When formatting part of an item description to "secret", the player is still able to read it when editing the text:
![image](https://github.com/vttred/ose/assets/49316726/fa8fe356-24d7-4ed6-9ecc-68e1b90962b8)
I can't find any permissions pertaining to this, either.

Ideally I would still like my players to be able to create and edit item descriptions, I just don't want them to see or edit the secret descriptions. A "reveal" feature would be a nice-to-have, but I'd be fine to be able to just copy/paste them over.

Thanks!

**Comment by anthonyronda** [comment]
If a user has permission to edit the item (including the description) it is expected that they have permission to read the secrets on that item. Essentially, an owner of an item gets to write and read secrets on that item.

OSE has no control over how secrets work, which is core Foundry VTT functionality. I think you should re-submit this as a feature request directly to Foundry VTT.
