### ISSUE TITLE
Errors when running Combat Tracker in OSE

### ISSUE THREAD

**Issue by PXR5** [vttred/ose#474]
### What happened?

Running combat with Combat Tracker in OSE with Group Initiative

Select Actor tokens in the Scene
Right click and Select Combat State
Errors are reported in the console
Click Begin Combat
Combat Tracker rolls initiative but typically does not select the first combatant - I manually reselect before continuing

### What is the expected behaviour?

Combat Tracker should begin without errors and the first combatant should be selected by default

### Relevant Errors and Warnings

```shell
The following errors are reported as the Combat tracker starts

commons.js:2065 Error: You are accessing PlaceableObject#data which is no longer used and instead the Document class should be referenced directly as PlaceableObject#document.
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    at Object.logCompatibilityWarning (commons.js:2054:19)
    at Token.get (foundry.js:28134:23)
    at Object.addCombatant (combat.js:295:47)
    at Object.fn (ose.js:180:15)
    at #call (foundry.js:730:20)
    at Hooks.call (foundry.js:712:38)
    at #preCreateDocumentArray (foundry.js:13483:44)
    at async ClientDatabaseBackend._createDocuments (foundry.js:13369:22)
logCompatibilityWarning @ commons.js:2065
get @ foundry.js:28134
addCombatant @ combat.js:295
(anonymous) @ ose.js:180
#call @ foundry.js:730
call @ foundry.js:712
#preCreateDocumentArray @ foundry.js:13483
await in #preCreateDocumentArray (async)
_createDocuments @ foundry.js:13369
create @ commons.js:8624
await in create (async)
createDocuments @ commons.js:7953
createEmbeddedDocuments @ commons.js:8210
toggleCombat @ foundry.js:42576
await in toggleCombat (async)
toggleCombat @ foundry.js:55696
_onToggleCombat @ foundry.js:82557
_onClickControl @ foundry.js:82482
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
9commons.js:2065 Error: You are accessing PlaceableObject#data which is no longer used and instead the Document class should be referenced directly as PlaceableObject#document.
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    at Object.logCompatibilityWarning (commons.js:2054:19)
    at Token.get (foundry.js:28134:23)
    at Object.addCombatant (combat.js:295:47)
    at Object.fn (ose.js:180:15)
    at #call (foundry.js:730:20)
    at Hooks.call (foundry.js:712:38)
    at #preCreateDocumentArray (foundry.js:13483:44)
    at async ClientDatabaseBackend._createDocuments (foundry.js:13369:22)
    at async Combatant.createDocuments (commons.js:7953:23)
    at async Token.toggleCombat (foundry.js:55696:5)
logCompatibilityWarning @ commons.js:2065
get @ foundry.js:28134
addCombatant @ combat.js:295
(anonymous) @ ose.js:180
#call @ foundry.js:730
call @ foundry.js:712
#preCreateDocumentArray @ foundry.js:13483
await in #preCreateDocumentArray (async)
_createDocuments @ foundry.js:13369
create @ commons.js:8624
await in create (async)
createDocuments @ commons.js:7953
createEmbeddedDocuments @ commons.js:8210
toggleCombat @ foundry.js:42576
await in toggleCombat (async)
toggleCombat @ foundry.js:55696
_onToggleCombat @ foundry.js:82557
_onClickControl @ foundry.js:82482
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
foundry.js:21516 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'combatantId')
    at Combat._manageTurnEvents (foundry.js:21516:53)
    at Combat._onCreate (foundry.js:21354:10)
    at ClientDatabaseBackend.callback (foundry.js:13544:11)
    at foundry.js:13517:43
    at Array.map (<anonymous>)
    at #handleCreateDocuments (foundry.js:13517:33)
```

### Additional Support Details

Foundry Virtual Tabletop: Version 11 Stable, 11.313
Game System: ose, 1.9.3
Active Modules: 18
Performance Mode: 2

OS: Unknown
Client: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
GPU: ANGLE (Apple, Apple M1 Max, OpenGL 4.1)
Max Texture Size: 16384

Scene: 5400 x 3552 | Grid Size: 100 | Padding Percentage: 0.25
Walls: 0 | Ambient Lights: 0 | Ambient Sounds: 0 | Tiles: 1 | Tokens: 10

Actors: 60 | Items: 63 | Journal Entries: 8 | Rollable Tables: 5 |
Playlists: 0 | Compendium Packs: 13 | Chat Messages: 184

### Foundry VTT Core Version

V11

### Please update your browser regularly. Which (updated) browsers are you seeing the problem on?

Microsoft Edge, Other

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anthonyronda** [comment]
Sorry for the delay. We've previously investigated the problem of V10 deprecation warnings, similar to those you've pasted from the console log (#211). At least in those cases we decided that we could not appropriately address them without removing V9 support

I will still investigate the issue this week. Currently I believe it's the same as #297, a problem whose solution has eluded us for quite some time

**Comment by Rughalt** [comment]
As this refers to older combat tracker implementation, I am closing this issue.
