### ISSUE TITLE
Monk's Active Tile Trigger "attack" method  does not work with actors/weapons of an  OSE system

### ISSUE THREAD

**Issue by Juppstein** [vttred/ose#477]
### What happened?

Create an actor "Pit Trap" with a weapon (i.e. a club) that deals damage and acts as a "trap"
Create a scene  and set up a tile with the following config:

![Selection_002](https://github.com/vttred/ose/assets/8590930/838fb7eb-a803-42b8-b30a-af936f537fb4)

![Selection_003](https://github.com/vttred/ose/assets/8590930/840e55dd-5e82-4ca1-b1d5-a3e4da34da42)

Verifry that the tile is active  and choose a monster or a player token and have it enter the tile so it triggers the event. The token gets targeted but the attack never happens. 

I verified that MATT is running as it should by trying other trigger methods like teleport, pause or show/hide and those did work as intended. But as soon as an actor/token with an item like a weapon is involved the triggers are not executed as intended. 

### What is the expected behaviour?

The moment the token enters the tile the damage effect from MATT should trigger and deal damage accordingly. 

Foundry VTT v11 build 314
OSE 1.9.3
Monk's Active Tile Trigger (MATT) 11.11
Foundry is running on a headless Ubuntu 22.04 Server 

Here are the quotes from the dev over on the IronMonk Discord server ( https://discord.gg/Aap79Ftm ) when I asked them about the issue:

me:
> Hi, sorry to bother. But I have a strange issue with active tiles where the attack method is not being triggered when entering a tile. Other things like hide/show or showing images work. According to the history all actors entering the tile are registered. I am using the OSE system but I think I've seen others saying that they use MATT successfully with OSE. Here is my setup, it's pretty simple

Exile:
> if everything else fires except the attack action, prolly not compatible or an update might have broken it if it used to work

Crowguard:
> Not at my PC to check, but try changing the Type in the drop-down to... whatever the third option is called

me:
> That would be "Use". Nope, that does not work as well 😕  Is there any way for me to trace back what happens here in the background?

Crowguard:
> You can hit F12. I checked on it earlier, I can't even get the Attack action to recognize weapons on that system

me:
> Yeah well, not sure what those folks meant by "its working on my side" but I didnt get it to work on my side here either, regardless of what I tried
what i did see is that the actor token gets targeted but the attack never gets called. oh well, I'll get back to the OSE guys and see if there is a way to get this working...hopefully

Crowguard:
> I'm guessing whatever they're doing with items is completely different behind the scenes from how Foundry & most systems handle them. Usually if the Attack action in a system doesn't work, the weapon/spell is still selectable. It just errors and fails

### Additional Support Details

Foundry Virtual Tabletop: Version 11 Stable, 11.314
Game System: ose, 1.9.3
Active Modules: 31
Performance Mode: 2

OS: Ubuntu 22.04 LTS 
Client: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
GPU: ANGLE (NVIDIA Corporation, NVIDIA GeForce RTX 2060/PCIe/SSE2, OpenGL 4.5.0)
Max Texture Size: 32768

Scene: 3248 x 3248 | Grid Size: 100 | Padding Percentage: 0.25
Walls: 62 | Ambient Lights: 8 | Ambient Sounds: 3 | Tiles: 6 | Tokens: 20

Actors: 45 | Items: 0 | Journal Entries: 10 | Rollable Tables: 0 |
Playlists: 1 | Compendium Packs: 31 | Chat Messages: 0

### Foundry VTT Core Version

V11

### Old-School Essentials Core Version

1.9.3

### Please update your browser regularly. Which (updated) browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anthonyronda** [comment]
@Juppstein I saw that this was addressed on Monk's side here https://github.com/ironmonk88/monks-active-tiles/blob/main/CHANGELOG.md#version-1112

Ok to close the issue?

**Comment by Juppstein** [comment]
Yes, this can be closed, thanks!
