### ISSUE TITLE
Error in the weight value on item vs Encumbrance bar

### ISSUE THREAD

**Issue by IGALEGOI** [vttred/ose#48]
I noticed a bug in relation to setting the weight of the items, I entered with weight 100, but it is computing 80. Could someone confirm this? 

![image](https://user-images.githubusercontent.com/97805442/150168409-a899d910-8a70-4293-8f79-d2cab037b8da.png)

**Comment by engleback** [comment]
That is per rules, all equipment is 80 coins, only weapons, armour and treasure are counted separately.

**Comment by IGALEGOI** [comment]
> That is per rules, all equipment is 80 coins, only weapons, armour and treasure are counted separately.

I believe this rule only applies if the item is in the backpack, which in this case can be used as a container. 

The player can use other means and ways to carry the item, which such a rule is no longer applicable.

Also, the DM may judge that such a backpack can fit up to a certain amount of coins. If it exceeds that limit, the master may inform the player that there is no more room. Having to find another way to carry. 


**Obs.**
This is one thing that can be improved with the container idea, where the weight of the item does not matter. But it does contribute by adding/subtracting the weight of the container. I talked about this in another post.

**Comment by engleback** [comment]
There is nothing in the rules about whether an item is in a backpack or not.

From the Classic Fantasy Rules Tome (v1.3) page 113 under Encumbrance (my emphasis)

Option 2: Detailed Encumbrance
Treasure: The weight of coins and other
treasure carried is tracked.
Equipment: The weight of the character’s
armour and weapons is also tracked
(the weight of these items is listed in the
equipment list). <b>Miscellaneous adventuring
gear (backpack, spikes, sacks, etc.)
may be counted as 80 coins of weight.</b>
Movement rate: The character’s movement
rate is based on the total weight of
all significant items carried, including
treasure, weapons, and armour.

I'm assuming you are referring to Detailed Encumbrance, the Basic Encumbrance option does not take the weight of anything into account, only the type of armour and whether treasure is carried or not.

**Comment by IGALEGOI** [comment]
Understood, so if I want such an item to weigh according to its value, I should use the treasure tab.


### **What I think**

The "rules" works like a toolkit, and it is up to the master to decide how he will use it. You can change it as a house rule, or even have the possibility to play another OSR system with OSE.

If you make the rule too rigid, it will take away the user's agency in deciding that. **PS.** It is always good to avoid **hard code**, as much as possible. 

I will use this image as an example (Fantasy Grounds inventory), the default system does not add weight to the items, only the backpack item by default has 80 weight. 

BUT if you want, it is possible change the weight.

![image](https://user-images.githubusercontent.com/97805442/150385719-e2c91148-90f8-4158-a9e4-56ca63641d4c.png)

### **What would I do?**
I would remove this restriction, and leave the items weightless, leaving only the backpack with 80.

**Comment by freohr** [comment]
The rules in OSE only specify weight for Armors, Weapons and Treasure, hand-waving weight of adventuring gear (tools and rations) at 80 coins if you have any (regardless of where a PC stores it on themselves). For me, saying that this 80 coins weight is only for gear in a backpack is an interpretation of the rules (which is not the interpretation coded in the system).

The other "official" (as in, written in the rules) encumbrance method is the Basic one. (one weight threshold for counting treasure, and speed when over or under this threshold is determined by what armor you wear), but this is not the topic of this discussion ^^

However, the foundry system adds a third encumbrance calculation method as "Complete", in which you can specify the weight of everything carried, and total weight is simply the sum of that. You can use this setting to do what you want to do, which is put the weight of the backpack at 80, the weight of anything in that at 0, and then the weight of everything outside the backpack to what you prefer.
