### ISSUE TITLE
Allow math in SPELL objects

### ISSUE THREAD

**Issue by frons79** [vttred/ose#488]
### What happened?

![Immagine 2023-11-26 103221](https://github.com/vttred/ose/assets/75011274/49600fe9-e650-4e18-a31b-503cb5f77e01)
I was editing the Hold Monster spell, and I realized it won't allow any math inside **Duration**, **Range** and **Roll** fields.

For instance Hold Monster's duration is _6 + 1/level_ turns and it would be logic to have _9_ turns in the spell card (considering a random level 3 character).

### What is the expected behaviour?

All the math, either with numbers or attributes, possible.

### Foundry VTT Core Version

V11

### Old-School Essentials Core Version

1.9.4

### Please update your browser regularly. Which (updated) browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anthonyronda** [comment]
Fixed in #499 to be released tonight
