### ISSUE TITLE
Treasure Weight not calculating correctly

### ISSUE THREAD

**Issue by Forelius** [vttred/ose#491]
### What happened?

Repro steps:
1. Set encumbrance type to anything except the new item-based option
2. Add GP or other treasure.
3. Weight for treasure is incorrect.

### What is the expected behaviour?

Weight for treasure displays the correct value. Example: 10 gp would have a weight of 10.

### Additional Support Details

Foundry Version: 11 Build 315
Old-School-Essentials Version: 1.10.1
No modules enabled

### Foundry VTT Core Version

V11

### Please update your browser regularly. Which (updated) browsers are you seeing the problem on?

Firefox, Microsoft Edge, Other

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by frons79** [comment]
This is a very urgent issue to be addressed, since it impacts also movement rate.

**Comment by anthonyronda** [comment]
Closed #500
