### ISSUE TITLE
Character Inventory not reading external values

### ISSUE THREAD

**Issue by Henrik-Bonsmann** [vttred/ose#498]
### What happened?

In the character inventory, the "Treasure" value, encumbrance bar and encumbrance break-points are missing. 
Inspecting the element reveals that several handlebars are returning null-values.

In `character-inventory-tab.html`:

```html
    <div class="field-long">
      {{system.treasure}} <i class="fas fa-circle"></i>
    </div>
```
(line 312 f)

```html
<section>
  {{#with @root.system.encumbrance}}
  <div class="encumbrance {{#if encumbered}}encumbered{{/if}}">
    <span class="encumbrance-bar" style="width:{{pct}}%"></span>
    <span class="encumbrance-label">{{value}} / {{max}}</span>
    {{#each steps as |s|}}
    <i class="encumbrance-breakpoint arrow-up" style="left:{{s}}%"></i>
    <i class="encumbrance-breakpoint arrow-down" style="left:{{s}}%"></i>
    {{/each}}
  </div>
  {{/with}}
</section>
```
(line 373 ff)

`{{system.treasure}}`, `{{pct}}` and `{{s}}` return `Null` while  `{{value}}`and `{{max}}` work fine.

### What is the expected behaviour?

Showing the treasure bar with movement break-points and the sum of treasure is vital for keeping bookkeeping low and the game fun and fast paced.

The inventory sheet can be seen working as intended in the guide:
https://ose.vtt.red/images/inventory.png

### Additional Support Details

Foundry: 11.315
OSE: 1.9.4
Client: foundry.exe

### Foundry VTT Core Version

None

### Please update your browser regularly. Which (updated) browsers are you seeing the problem on?

Other

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anthonyronda** [comment]
Closed #500
