### ISSUE TITLE
Confusing Damage Application Settings

### ISSUE THREAD

**Issue by justinthejaguar** [vttred/ose#5]
In order to get a read out for attack damage vs [enemy] one needs to target the token they wish to attack with the correct attacking creature selected.
![image](https://user-images.githubusercontent.com/38022481/147882513-777e4a2f-b1e0-4352-bf1f-d8f76475ea61.png)
This creates a card showing that the selected character inflicts damage. It does not automatically apply the damage to the target.
![image](https://user-images.githubusercontent.com/38022481/147882544-19f31aaa-6642-4a12-a45d-b83fc888ff8e.png)
Instead when you hover over the damage you are given a damage application button
![image](https://user-images.githubusercontent.com/38022481/147882558-c3216871-5634-4230-9030-e7eda6bfb8b4.png)
Hitting this button applies the damage to the selected token (not the targeted one that should be taking the damage.
![image](https://user-images.githubusercontent.com/38022481/147882580-a329274c-8de4-4603-ab75-f488129e72c6.png)

This method would probably make more sense if the targeting feature of printing the vs enemy card didn't exist, and if the player isn't targeting enemies it would always be helpful.

Is there anyway to update this so that the damage could be auto applied to the targeted token with the option to undo the damage in chat?

**Comment by anthonyronda** [comment]
@RabidOwlbear has a fix for this in #69, and created a setting to switch the behavior from selected tokens to targeted tokens. I'm curious, would you like the default to be selected or targeted?

**Comment by archibael** [comment]
I feel like default should be targeted.   If in the future we want to add something like attack icons that appear when the token is selected, we'll want to be able to select the attacker and the target simultaneously, and hard to do that (not to mention self-destructive ;) )  if the damage auto-applies to selected.

**Comment by justinthejaguar** [comment]
I think default to targeted is ideal if we have auto damage application, but after running the system quite a bit, I’ve noticed that the gm isn’t typically targeting the token of the pc, so I’m understanding the indent of it hitting the selected token instead.

**Comment by anthonyronda** [comment]
Merged the fix #70, which is a new PR to complete the contribution with translation strings
