### ISSUE TITLE
THAC0 Providing Incorrect Feedback

### ISSUE THREAD

**Issue by justinthejaguar** [vttred/ose#503]
### What happened?

Reproduction steps - Keep Descending AC/THAC0 settings
1. Attack without targeting THAC0 19. (no change)
2. Repeat until you get below a ten
3. Receive "Hits AC 9" regardless of missing roll.

### What is the expected behaviour?

This calculation is incorrect. The AC hit for THAC0 should follow the attack matrix in the books/SRD.

### Relevant Errors and Warnings

```shell
https://cdn.discordapp.com/attachments/929772978193956935/1213900434847301692/image.png?ex=65f727e0&is=65e4b2e0&hm=f065fe070e40a9e4b15e26bea8d48ad3d3390632152fde02970d435ce9d9df7f&

A character with THAC0 19 needs a 10 to hit AC 9.
A roll of 5 wouldn't hit anything.
```

### Additional Support Details

Electron - MacOS and Node.js on rpi.

### Foundry VTT Core Version

V11

### Old-School Essentials Core Version

1.10.1

### Please update your browser regularly. Which (updated) browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anthonyronda** [comment]
This behavior was purposefully changed in response to #333 and #332, which resulted in the following change

<img width="1169" alt="image" src="https://github.com/vttred/ose/assets/1410433/c20df2f3-ed08-438a-a25c-e52e533de1a5">

compare with @apewall's change

<img width="1165" alt="image" src="https://github.com/vttred/ose/assets/1410433/55bbd0bb-1308-402b-b622-7f44c092880f">

**Comment by anthonyronda** [comment]
Switched to design needed, because clearly there's something wrong with the design of the chat card if people keep changing their minds about whether an attack should hit without a target
