### ISSUE TITLE
v12?

### ISSUE THREAD

**Issue by osarusan82** [vttred/ose#515]
### New Feature or Changed Behaviour

Will this be updated to work with Foundry VTT version 12?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Ondath** [comment]
A month has passed and OSE has been utterly incompatible with v12, it would be really great if the update could be made!

**Comment by chrisesharp** [comment]
I have to admit, OSE is the last system I use that is preventing me from upgrading to V12.

**Comment by osarusan82** [comment]
> A month has passed and OSE has been utterly incompatible with v12, it would be really great if the update could be made!

At this point I'm pretty sure it's been abandoned entirely. Time to look for a new system.

**Comment by Rughalt** [comment]
V12 compatible version was released lately, closing the issue
