### ISSUE TITLE
Languages not displaying

### ISSUE THREAD

**Issue by Taliesin1** [vttred/ose#516]
I entered some Dolmenwood languages in the OSE Settings but in my Actor setups, the languages being displayed are generic fantasy languages, I guess from OSE?

First I thought maybe I shouldn't have spaces in my comma-separated list, so I removed them, but the results were the same.

Here's a screenshot to show how I've entered them.

Thanks!

<img width="1367" alt="Screenshot 2024-06-07 at 9 30 48 AM" src="https://github.com/vttred/ose/assets/10515719/58867c27-5c01-4703-88f8-c4b373915b3d">

**Comment by justinthejaguar** [comment]
I noticed this before. Did you try reloading after updating?

**Comment by Taliesin1** [comment]
Yes. Reloading fixed it, thank you.
