### ISSUE TITLE
The button to show in the Chat (the eye) does not work

### ISSUE THREAD

**Issue by NachoTeller** [vttred/ose#524]
### What happened?

In the Abilities or Spells, we touch the Eye, and nothing happens

### What is the expected behaviour?

The information of the Ability or Spell should be displayed in the chat.

### Foundry VTT Core Version

V11

### Old-School Essentials Core Version

1.10.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by apewall** [comment]
Culprit is CHAT_MESSAGE_STYLES is not a part of v11.

https://github.com/vttred/ose/blob/1bf7f8fe09343458fdf7d2664bf6c920d3dcf399/src/module/item/entity.js#L402
