### ISSUE TITLE
[V12] Group Initiative Plain Doesn't Work

### ISSUE THREAD

**Issue by NekohimeMusou** [vttred/ose#526]
### What happened?

In short, grouped initiative is _completely_ broken in v12 to the point where you can't begin a combat.

I don't know anyone actively using v12 to run an OSE campaign, so I could be missing something important or there could be workarounds for this and the individual init glitch (issue pending) I don't know of. If not, the combination of both problems is a bad enough show stopper that I think it's inaccurate to claim the system is v12 compatible.

This happens both on a copy of my current campaign world and in a completely fresh OSE world with no mods enabled.

Reproduction steps:

1. Set Initiative to Grouped. This behavior occurs _regardless of the Initiative Persistence setting_. Mine was set to Keep while I did this.
2. Create a new combat and add some PCs and monsters. Set their groups appropriately.
3. Click the Begin Combat button.
4. Initiative is (re)rolled automatically, regardless of whether it was already rolled.
5. An error notification (pictured) appears, and combat does not begin.
![group-error-notif](https://github.com/vttred/ose/assets/37454858/ec122fd8-dca4-4174-b7ec-5585d81a3e6e)
6. Repeat steps 3 through 5 as many times as you like; initiative is rerolled each time, but combat never begins

### What is the expected behaviour?

When Begin Combat is clicked, combat should begin and the first combatant's turn should come up. Also, initiative should probably not be rerolled if it was already rolled before combat began, especially with Initiative Persistence set to Keep.

### Relevant Errors and Warnings

```shell
Cannot assign to read only property '_id' of object '#<Combatant>'

TypeError: Cannot assign to read only property '_id' of object '#<Combatant>'
    at SchemaField._cleanType (foundry-esm.js:7847:20)
    at SchemaField.clean (foundry-esm.js:7342:19)
    at foundry-esm.js:8838:41
    at Array.map (<anonymous>)
    at EmbeddedCollectionField._cleanType (foundry-esm.js:8838:20)
    at EmbeddedCollectionField.clean (foundry-esm.js:7342:19)
    at SchemaField._cleanType (foundry-esm.js:7847:28)
    at SchemaField.clean (foundry-esm.js:7342:19)
    at Combat.cleanData (foundry-esm.js:10295:26)
    at Combat.validate (foundry-esm.js:10407:48)
```

### Additional Support Details

Foundry Virtual Tabletop: Version 12 Stable, 12.328
Game System: ose, 1.10.3
Active Modules: 0
Performance Mode: 1

OS: Windows 10.0.0 x86 (64-bit)
Client: Not/A)Brand/8.0.0.0
GPU: ANGLE (Intel, Intel(R) UHD Graphics 630 (0x00003E9B) Direct3D11 vs_5_0 ps_5_0, D3D11)
Max Texture Size: 16384

Scene: 3840 x 1920 | Grid Size: 100 | Padding Percentage: 0
Walls: 0 | Ambient Lights: 5 | Ambient Sounds: 0 | Tiles: 1 | Tokens: 5
Largest Texture: 3840 x 1920 

Actors: 4 | Items: 0 | Journal Entries: 0 | Rollable Tables: 0 |
Playlists: 0 | Compendium Packs: 0 | Chat Messages: 4

World Scripts: 

### Foundry VTT Core Version

None

### Please update your browser regularly. Which (updated) browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PXR5** [comment]
I confirm this is still an issue and is blocking me from upgrading to V12.
