### ISSUE TITLE
Old-School Essentials OGL Content gone? / Confusion about different repos and outdated READMEs

### ISSUE THREAD

**Issue by tbsvttr** [vttred/ose#53]
In the "Old School Guide" (found under Game Settings > Help and Documentation) a module "Old-School Essentials OGL Content" is referenced. One should install it, but I was not able to find it. Was it deleted, or am I just not able to find it? I guess either a link should be added to the "Old School Guide" or the reference should be removed.

**Comment by tbsvttr** [comment]
I guess now this is the one? https://gitlab.com/mesfoliesludiques/foundryvtt-ose-content

Which opens the question of what the relationship of this repo is to this repo: https://gitlab.com/mesfoliesludiques/foundryvtt-ose

Which one should be installed?

**Comment by tbsvttr** [comment]
And now I even found this: https://github.com/vttred/ose-content

This is quite confusing. Am I missing something, or are quite duplicated repos and outdated README files going on here?

**Comment by anthonyronda** [comment]
Yes, outdated READMEs haven't been made a priority. Apologies for the confusion. I'll keep this issue open to track all the places we've yet to update repo links.

However the `ose-content` itself hasn't moved or been removed, all of the places you've mentioned are where it's accessible from, as well as:
https://foundryvtt.com/packages/ose-content/

Both `ose-content` repositories are exactly the same for now, but if a new update needs to be pushed, it will be to the `vttred`/`ose-content` repository on GitHub.

This `ose` repository is the only one being currently maintained for FVTT V9 and later. What is the relationship between us and the original maintainer of `ose` package? We're both fans of open source software :)

**Comment by anthonyronda** [comment]
I believe all mentions of the old repository have been removed in the latest commits. The docs aren't perfect, but it's a start. The remaining GitLab repo mentions that were replaced were:

- manifest url in the README
- a link to the GL issues page in the docs
