### ISSUE TITLE
[V11] Spell does not show up in chat

### ISSUE THREAD

**Issue by JordanRR** [vttred/ose#530]
### What happened?

1. I click on a spell that does not contain a die roll (ex. Charm Person) on a PC sheet.
2. It does not send to chat.

### What is the expected behaviour?

It should show in chat.

### Relevant Errors and Warnings

```shell
entity.js:402 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'OTHER')
    at ze.show (entity.js:402:39)
    at async ze.spendSpell (entity.js:195:18)
injected.js:42 [USO] Button detection aborting due to timeout.
game:1 The keyword 'inner-spin-button' used on the 'appearance' property was deprecated and has now been removed. It will no longer have any effect.
foundry.js:3687 Foundry VTT | Synchronized official game time in 28ms
entity.js:402 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'OTHER')
    at ze.show (entity.js:402:39)
    at async ze.spendSpell (entity.js:195:18)
```

### Additional Support Details

Using up to date Brave browser.

Foundry Virtual Tabletop: Version 11 Stable, 11.315
Game System: ose, 1.10.3
Active Modules: 67
Performance Mode: 2

OS: Unknown
Client: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
GPU: ANGLE (NVIDIA, NVIDIA GeForce GTX 1660 SUPER (0x000021C4) Direct3D11 vs_5_0 ps_5_0, D3D11)
Max Texture Size: 16384

Scene: 1716 x 2156 | Grid Size: 50 | Padding Percentage: 0.5
Walls: 0 | Ambient Lights: 0 | Ambient Sounds: 0 | Tiles: 0 | Tokens: 35

Actors: 632 | Items: 349 | Journal Entries: 1502 | Rollable Tables: 100 |
Playlists: 0 | Compendium Packs: 89 | Chat Messages: 233

### Foundry VTT Core Version

V11

### Please update your browser regularly. Which (updated) browsers are you seeing the problem on?

Other

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JordanRR** [comment]
The problem does not happen with speels including dice roll (ex. Magic Missile).

**Comment by apewall** [comment]
Same issue as https://github.com/vttred/ose/issues/524

**Comment by NekohimeMusou** [comment]
#531 fixes this. I tried Magic Missile, Charm Person, and Sleep and they all work.
