### ISSUE TITLE
Wrong Weight Calculation - Containers

### ISSUE THREAD

**Issue by rwelloso** [vttred/ose#543]
### What happened?

In the images I show the item and the wrong weight calculation. If I add a second item (duplicate the first one), it will not generate this weight error.

![Captura de Tela 2024-10-12 às 20 38 45](https://github.com/user-attachments/assets/28e25751-d080-4ead-988a-e2a7eed2ef90)
![Captura de Tela 2024-10-12 às 20 38 54](https://github.com/user-attachments/assets/ba76b691-1ea4-4ca4-b03e-d7a7d8673e8e)

### What is the expected behaviour?

Every first item that goes to the Container has its weight calculated incorrectly.

Fix this bug so that it searches for the information contained in the item and no longer generates this weight error.

### Relevant Errors and Warnings

```shell
It does not generate an error message.
```

### Additional Support Details

**Foundry Virtual Tabletop:** _Version 12 Stable, 12.331_

**Game System:** ose, 2.0.2

**Active Modules:** _1_

**Performance Mode:** _2_

**OS:** _macOS 10.15.7 x86 (64-bit)_

**Client:** _Chromium/128.0.0.0_

**GPU:** _ANGLE (Intel Inc., Intel HD Graphics 4000 OpenGL Engine, OpenGL 4.1)_

**Max Texture Size:** _16384_

No viewed scene

Actors: 1 | Items: 0 | Journal Entries: 0 | Rollable Tables: 0 |
Playlists: 0 | Compendium Packs: 25 | Chat Messages: 0

World Scripts: 

### Foundry VTT Core Version

V11

### Old-School Essentials Core Version

OSE 2.0.2

### Please update your browser regularly. Which (updated) browsers are you seeing the problem on?

Other

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Rughalt** [comment]
According to RAW:

> Equipment: The weight of the character’s armour and weapons is also tracked (the weight of these items is listed in the equipment list). Miscellaneous adventuring gear (backpack, spikes, sacks, etc.) may be counted as 80 coins of weight.

If you want the behaviour you are expecting, you should use Complete Encumbrance (after @wyrmisis)
