### ISSUE TITLE
Option to delete item after it is moved to a character inventory

### ISSUE THREAD

**Issue by engleback** [vttred/ose#63]
Include a flag on an item that when the item is moved from the item list to a character inventory it is deleted from the item list.

Could be used to distribute treasure or items to players, GM creates in the item list and the player moves to a character.

**Comment by anthonyronda** [comment]
You mean from the Item Directory? (Right sidebar) Have you tried Item Piles yet?

Try it! It's really good. After you have let me know if you still want this.

I think your suggestion makes for a relatively poor user experience. There's at least one other enhancement request that wants a way to distribute treasures without (accidental) duplicate rewards given: #45 

I'd love to hear more people share their thoughts.

**Comment by bakbakbakbakbak** [comment]
I agree @anthonyronda, I think this would be better suited as implemented by Item Piles or similar.

**Comment by anthonyronda** [comment]
I think it's safe to close but @engleback is welcome to reopen if there is more to say
