### ISSUE TITLE
Feature Request: Remove Spell Level Cap

### ISSUE THREAD

**Issue by justinthejaguar** [vttred/ose#84]
The spell level currently cap at level 6 as appears in the basic rules. It would make the system more cross compatible if we removed the spell level cap and allowed higher level spells to be used as suggested in the [Old-School Essentials Adaptation](https://cdn.shopify.com/s/files/1/0017/2330/1933/files/Old-School_Essentials_-_Adaptation_Guidelines_v1-3.pdf?v=1631260603) guide for Higher Level Spells.

**Comment by bakbakbakbakbak** [comment]
I believe this is fixed with the improved data models for spells, right @wyrmisis ?

**Comment by anthonyronda** [comment]
@justinthejaguar you're free to reopen if I'm mistaken

I can't remember what the restriction was previously but I'm able to make higher level spells currently so I think this enhancement is complete as bakbak said :)
